# Generated by Django 5.1 on 2026-01-30 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo_barra', models.CharField(max_length=100)),
                ('precio_costo', models.FloatField()),
                ('precio_venta', models.FloatField()),
                ('stock_actual', models.FloatField()),
                ('stock_maximo', models.FloatField()),
                ('stock_minimo', models.FloatField()),
                ('unidad_medida', models.CharField(choices=[('unidad', 'Unidad'), ('kg', 'Kilogramo')], default='unidad', max_length=10)),
                ('es_granel', models.BooleanField()),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='inventory.producto')),
            ],
        ),
    ]
